name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
          cd VehicleControlUnit\UnitTests
          mkdir build
          cd build
          cmake ..
          cmake --build . 
    - name: Run unit tests
      run: |
          cd VehicleControlUnit\UnitTests\build
          .\Debug\unit-tests.exe